var myNumber = 10;
console.log(myNumber);
var yourNumber = 17;
console.log(yourNumber);
myNumber === yourNumber;
console.log(myNumber === yourNumber);
myNumber < yourNumber;
console.log(myNumber < yourNumber);
myNumber > yourNumber;
console.log(myNumber > yourNumber);